# Generated by Django 5.2.1 on 2025-06-04 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание задачи')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('done', 'Done')], default='new', max_length=20, verbose_name='статус')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='срок задачи')),
                ('tags', models.JSONField(blank=True, null=True, verbose_name='теги')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'задача',
                'verbose_name_plural': 'задачи',
                'ordering': ('id',),
            },
        ),
    ]
